[package]
name = "chili-py"
version = "0.10.2"
edition = "2024"
authors = ["The Chili Authors <purple-chili@hotmail.com>"]
description = "Python bindings for chili-core EngineState"

[lib]
name = "engine_state"
crate-type = ["cdylib"]

[dependencies]
chili-core = { path = "../chili-core" }
chili-op = { path = "../chili-op" }
indexmap = "2.14.0"
polars = { version = "0.55.2" }
pyo3 = { version = "0.29.2", features = ["abi3-py310", "chrono"] }
pyo3-polars = { version = "0.28.0", features = ["lazy"] }
chrono = { version = "0.4" }
