use std::path::PathBuf;

use crate::assert_eq_chili_expr;

#[test]
fn test_sub_expr() {
    let mut src_path = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    src_path.push("tests/chili/src/sub.chi");
    let src_path = src_path.to_str().unwrap();
    let src = std::fs::read_to_string(src_path).unwrap();

    assert_eq_chili_expr(
        &src,
        vec![
            "block",
            "  assign",
            "    id",
            "    fn",
            "      id",
            "      id",
            "      block",
            "        binary",
            "          id",
            "          binary op",
            "          id",
            "        call",
            "          id",
            "          Int'1'",
            "        nil",
            "  assign",
            "    id",
            "    fn",
            "      block",
            "        assign",
            "          id",
            "          call",
            "            id",
            "            Symbol'`chili://:18000:sub1:token789'",
            "        call",
            "          id",
            "          id",
            "          Symbol'`.sub.recover'",
            "        assign",
            "          id",
            "          call",
            "            id",
            "            list",
            "              Symbol'`.tick.subscribe'",
            "              list",
            "        binary",
            "          bracket",
            "            id",
            "          binary op",
            "          call",
            "            id",
            "            Int'2'",
            "        call",
            "          id",
            "          call",
            "            id",
            "            Int'0'",
            "          Int'0'",
            "          call",
            "            id",
            "            Int'1'",
            "          list",
            "          Bool'1b'",
            "        call",
            "          id",
            "          id",
            "        nil",
            "  assign",
            "    id",
            "    fn",
            "      id",
            "      block",
            "        call",
            "          id",
            "          id",
            "        assign",
            "          id",
            "          call",
            "            id",
            "            list",
            "              Symbol'`.tick.subscribe'",
            "              list",
            "        call",
            "          id",
            "          call",
            "            id",
            "            Int'0'",
            "          call",
            "            id",
            "            Int'0'",
            "          call",
            "            id",
            "            Int'1'",
            "          list",
            "          Bool'1b'",
            "        call",
            "          id",
            "          id",
            "        nil",
            "  call",
            "    id",
            "    (0 arg)",
        ],
    )
}

#[test]
fn test_pub_expr() {
    let mut src_path = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    src_path.push("tests/chili/src/pub.chi");
    let src_path = src_path.to_str().unwrap();
    let src = std::fs::read_to_string(src_path).unwrap();

    assert_eq_chili_expr(
        &src,
        vec![
            "block",
            "  assign",
            "    id",
            "    call",
            "      id",
            "      Symbol'`chili://:18000'",
            "  assign",
            "    id",
            "    fn",
            "      block",
            "        assign",
            "          id",
            "          Int'10'",
            "        call",
            "          id",
            "          list",
            "            Str'publish'",
            "            id",
            "            Str'record'",
            "        call",
            "          id",
            "          list",
            "            Symbol'`.tick.upd'",
            "            Symbol'`trade'",
            "            table",
            "              column",
            "                id",
            "                binary",
            "                  id",
            "                  binary op",
            "                  Symbol'`a`b`c'",
            "              column",
            "                id",
            "                binary",
            "                  id",
            "                  binary op",
            "                  Float'1.0'",
            "              column",
            "                id",
            "                binary",
            "                  id",
            "                  binary op",
            "                  Int'10'",
            "              column",
            "                id",
            "                binary",
            "                  id",
            "                  binary op",
            "                  Symbol'`B`S'",
            "              column",
            "                id",
            "                binary",
            "                  id",
            "                  binary op",
            "                  call",
            "                    id",
            "                    Symbol'`'",
            "        call",
            "          id",
            "          list",
            "            Symbol'`.tick.upd'",
            "            Symbol'`quote'",
            "            table",
            "              column",
            "                id",
            "                binary",
            "                  id",
            "                  binary op",
            "                  Symbol'`a`b`c'",
            "              column",
            "                id",
            "                binary",
            "                  id",
            "                  binary op",
            "                  Float'1.0'",
            "              column",
            "                id",
            "                binary",
            "                  id",
            "                  binary op",
            "                  Float'1.0'",
            "              column",
            "                id",
            "                binary",
            "                  id",
            "                  binary op",
            "                  call",
            "                    id",
            "                    Symbol'`'",
            "        nil",
            "  call",
            "    id",
            "    Str'pub'",
            "    call",
            "      id",
            "      Symbol'`'",
            "    binary",
            "      call",
            "        id",
            "        Symbol'`'",
            "      binary op",
            "      Duration'1D00:00:00'",
            "    Duration'0D00:00:01'",
            "    Str'publish'",
        ],
    )
}
