use std::path::PathBuf;

use crate::assert_eq_pepper_expr;

#[test]
fn test_sub_expr() {
    let mut src_path = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    src_path.push("tests/pepper/src/sub.pep");
    let src_path = src_path.to_str().unwrap();
    let src = std::fs::read_to_string(src_path).unwrap();

    assert_eq_pepper_expr(
        &src,
        vec![
            "block",
            "  assign",
            "    id",
            "    fn",
            "      id",
            "      id",
            "      block",
            "        binary",
            "          id",
            "          binary op",
            "          id",
            "        call",
            "          id",
            "          Int'1'",
            "        nil",
            "  assign",
            "    id",
            "    fn",
            "      block",
            "        assign",
            "          id",
            "          unary",
            "            id",
            "            Symbol'`chili://:18000:sub1:token789'",
            "        call",
            "          id",
            "          id",
            "          Symbol'`.sub.recover'",
            "        assign",
            "          id",
            "          unary",
            "            id",
            "            list",
            "              Symbol'`.tick.subscribe'",
            "              list",
            "        binary",
            "          bracket",
            "            id",
            "          binary op",
            "          call",
            "            id",
            "            Int'2'",
            "        call",
            "          id",
            "          call",
            "            id",
            "            Int'0'",
            "          Int'0'",
            "          call",
            "            id",
            "            Int'1'",
            "          list",
            "          Bool'1b'",
            "        call",
            "          id",
            "          id",
            "        nil",
            "  assign",
            "    id",
            "    fn",
            "      id",
            "      block",
            "        call",
            "          id",
            "          id",
            "        assign",
            "          id",
            "          unary",
            "            id",
            "            list",
            "              Symbol'`.tick.subscribe'",
            "              list",
            "        call",
            "          id",
            "          call",
            "            id",
            "            Int'0'",
            "          call",
            "            id",
            "            Int'0'",
            "          call",
            "            id",
            "            Int'1'",
            "          list",
            "          Bool'1b'",
            "        call",
            "          id",
            "          id",
            "        nil",
            "  call",
            "    id",
            "    (0 arg)",
        ],
    )
}
