# https://taskfile.dev
version: "3"

vars:
  VERSION:
    sh: grep "version" Cargo.toml | head -1 | cut -d'"' -f 2

tasks:
  default:
    cmds:
      - cargo update --verbose
    silent: true

  test:
    cmds:
      - cargo test

  build:
    cmds:
      - cargo build --bin chili

  release:
    cmds:
      - cargo build --release --bin chili
      - ls -lh ./target/x86_64-unknown-linux-gnu/release/chili

  run:
    deps:
      - build
    cmds:
      - ./target/debug/chili  {{.CLI_ARGS}}

  run-pepper:
    deps:
      - build
    cmds:
      - ./target/debug/chili -P {{.CLI_ARGS}}

  dist:
    deps:
      - release
    cmds:
      - rm -f ./dist/chili*
      - mkdir -p ./dist
      - cp ./target/x86_64-unknown-linux-gnu/release/chili ./dist/chili
      - cd ./dist && tar -czvf chili_x86_64_linux_gnu_{{.VERSION}}.tar.gz ./chili

  podman-dist:
    cmds:
      - podman run --cpus=8 -it --rm -v $PWD:/build:Z -v $HOME/.cargo:$HOME/.cargo:Z manylinux2014 /bin/bash -i -c "task dist"

  install:
    deps:
      - podman-dist
    cmds:
      - cp ./dist/chili ~/bin

  tag:
    cmds:
      - git tag {{.VERSION}} && git push origin tag {{.VERSION}}

  clippy:
    cmds:
      - cargo clippy --fix --allow-dirty

  config-vim:
    cmds:
      - mkdir -p ~/.vim
      - cp -r ./vim-config/* ~/.vim/

  update-py-version:
    cmds:
      - sed -i "s/^version = \".*\"/version = \"{{.VERSION}}\"/" pyproject.toml

  release-py:
    deps:
      - test
    cmds:
      - rm -rf dist
      - maturin build --release --locked --out dist

  install-py:
    deps:
      - release-py
    cmds:
      - uv pip install dist/chili_pie*.whl
